#!/usr/bin/env bash

INPUT=${1:?arg_missing_input}
OUTPT=${2:?arg_missing_input}

log () {
  while [ "$1" ]; do
    echo "$1: ${!1}"
    shift
  done
}

input=$(find "$INPUT" -type f -name "*.mkv" | shuf -n 1)
output="$OUTPT"

log input output
echo -----------

total_frames="$(mediainfo  --Output="Video;%FrameCount%" "$input")"

random_frame=$((RANDOM % total_frames))

fps="$(mediainfo "$input" "--inform=Video;%FrameRate%" | cut -d '.' -f 1)"

time=$((random_frame/fps))

log total_frames random_frame fps time

ffmpeg -y -ss "$time" -i "$input" -frames 1 -s 1920x1080 -f image2 "$output"

# ##############################################################################
# ##############################################################################
# ##############################################################################

# fps="$(ffmpeg -i "$file" -vcodec copy -acodec copy -f null /dev/null 2>&1 | sed -n "s/.*, \(.*\) tbr.*/\1/p" | head -n 1)"
# fps="$(ffprobe "$file" 2>&1| grep ",* fps" | cut -d "," -f 5 | cut -d " " -f 2)"
# ffmpeg -ss 01:10 -i "$file" -frames 1 -s 1920x1080 -f image2 "$output"
# ffmpeg -y -i "$file" -vf "select=eq(n\,35)" -vframes 1 "$output"
# ffmpeg -i "$file" -vcodec copy -acodec copy -f null /dev/null 2>&1 | grep frame | cut -d ' ' -f 1 | sed s/frame=//
# echo "$TOTAL_FRAMES :: TOTAL_FRAMES"
# ffmpeg -ss 01:10 -y -i "$file" -frames 1 -s 1920x1080 -f image2 /home/meta/pics/wall/curr-1.png
# number=$(shuf -i 1-"$file_count" -n 1)
# od -A n -N 2 -t u2 /dev/urandom
# head -200 /dev/urandom | cksum
# head -200 /dev/urandom | cksum | cut -f1 -d " "
# echo ">> $(( $RANDOM % $file_count + 1 ))"
# echo "$file_count :: file_count"
# echo "$number :: number"
# ffmpeg -ss 01:10 -i Cyberpunk-Edgerunners-0"$number".mkv -frames 1 -s 1920x1080 -f image2 /home/meta/pics/wall/curr-1.png
# ffmpeg -ss 01:10 -y -i /usr/local/meta/tr/Cyberpunk-Edgerunners/Cyberpunk-Edgerunners-0"$number".mkv -frames 1 -s 1920x1080 -f image2 /home/meta/pics/wall/curr-1.png
# ffmpeg -i Cyberpunk-Edgerunners-.mkv -vf fps=1/60 img%03d.jpg
# ffmpeg -i Cyberpunk-Edgerunners-.mkv -vf fps=1/60 img%03d.jpg

